### PR TITLE
Drop static (duplicated) docs, in favour of dynamic readthedocs.io

### PR DESCRIPTION
**Pull request by slyon**
## Done

* Drop "Reference" and "Examples" from the navigation. These are now dynamically rendered from the [upstream repository](https://github.com/canonical/netplan/tree/main/doc) via Sphinx: [netplan.readthedocs.io](https://netplan.readthedocs.io)
* Implemented redirects of `/reference` and `/examples` to the new docs page
* Related to #233, which got stuck for several reasons

## QA

* Executed `./run` + visual & technical inspection
* I'm not sure if I implemented the redirects correctly (as I'm not a web-dev), but they seem to be working. – feel free to modify if needed, edits to my branch are open!

## Issue / Card

FR-2853, in accordance with [Netplan - documentation content objectives (23.04 plans)](https://docs.google.com/document/d/1n47hwLmR6GiLJX0t5w2_uGngQ3b3jfpPN8H8knIJ9vQ/edit#heading=h.luz5adp90tcl)

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by juanruitina** [comment]
UX looks good. One comment though: /reference is linking to [YAML configuration](https://netplan.readthedocs.io/en/latest/netplan-yaml.html) instead of [Reference](https://netplan.readthedocs.io/en/latest/reference.html). Is this intentional? I'd suggest to link to the latter, particularly now that some of the text previously under "General structure" (which seems useful) is available in the latter and not in the former. (And there's no harm in surfacing references for API, CLI and D-bus to whoever uses the old link.)

**Comment by slyon** [comment]
Thanks for the review! I fixed the Footer accordingly.

The redirect of "/reference" to [YAML configuration](https://netplan.readthedocs.io/en/latest/netplan-yaml.html) is indeed intentional. "YAML configuration" was split out into it's own page inside the new docs, but it used to be located under "/reference" in the past. We have lots of places that link to anchors in that page, so we want links (like https://netplan.io/reference#properties-for-device-type-ethernets) to redirect to the correct location inside the new "YAML configuration" sub-page, in order not to break those links (e.g. from AskUbuntu, etc).

**Comment by juanruitina** [comment]
Oh, that's definitely a good reason to link there, yep. Perhaps you can still add some of the info that used to be under "General structure" to this page for a bit of context, your call. This LGTM in any case. Thanks for the tweak!

**Review by carkod — APPROVED** [review]
LGTM

**Comment by slyon** [comment]
> Perhaps you can still add some of the info that used to be under "General structure" to the YAML config page for a bit of context, your call.

I'll leave it as-is, as this "General structure" information was explicitly removed by request of @evildmp for Diataxis reasons.

**Pull request merged**
