### PR TITLE
Use template finder markdown

### PR DESCRIPTION
**Pull request by carkod**
## Done

Netplan team uses a markdown template to update the reference page, we
are adpating it by using the template finder frontmatter parsing
abilities to replace the Jinja template

## QA

- Check that https://netplan-io-241.demos.haus/reference works

## Issue / Card
Fixes https://github.com/canonical/web-squad/issues/5845

### CODE REVIEW

**Review by slyon — APPROVED** [review]
Thanks for providing the demo, LGTM!

+1

**Comment by anthonydillon** [comment]
Wouldn't it be better to automatically generate the TOC?

**Comment by minkyngkm** [comment]
In the demo. there are some parts looking a bit different from the live one.
e.g. there are many places wrapped with `blockquote`. Wondering if needs to be fixed @carkod 

live page:
image
demo:
image

**Comment by carkod** [comment]
> Wouldn't it be better to automatically generate the TOC?
Added

**Comment by carkod** [comment]
> In the demo. there are some parts looking a bit different from the live one. e.g. there are many places wrapped with `blockquote`. Wondering if it needs to be fixed @carkod
> 
> live page: image demo: image

Nope, I did mention it to Lukas, he is fine with it because `>` should actually render as a blockquote. That Markdown actually comes from the [template they use](https://github.com/canonical/netplan/blob/main/doc/netplan-yaml.md)

**Comment by slyon** [comment]
+1 autogenerated TOC is nicer, and using blockquotes is fine (as expected).

**Review by minkyngkm — APPROVED** [review]
LGTM 👍

**Pull request merged**
